root_dir: /home/ubuntu/data/belson/test_seq_service/illumina
sample: 
  Salmonella_isangi_17-762-33892: 
    r1: /home/ubuntu/data/belson/test_seq_service/illumina/Salmonella_isangi_17-762-33892/17762-33892_1_71_bbduk_1.fastq.gz
    r2: /home/ubuntu/data/belson/test_seq_service/illumina/Salmonella_isangi_17-762-33892/17762-33892_1_71_bbduk_2.fastq.gz