root: /home/ubuntu/data/belson/test_seq_service
kraken_db: /home/ubuntu/data/belson/test_seq_service/kraken
refSek_db: /home/ubuntu/data/belson/bacteria-refseq/
bakta_db: /home/ubuntu/data/belson/bakta/db/db
medaka_mod: r941_min_sup_g507
ref_genome: /home/ubuntu/data/belson/reference/2021.04.01/17762-33892_1_71_contigs.fa
samples:
  - barcode06_CHF10J1